# Generated by Django 4.2.16 on 2026-03-23 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('state', models.CharField(choices=[('session_created', 'Session Created'), ('story_selected', 'Story Selected'), ('story_analyzed', 'Story Analyzed'), ('plan_generated', 'Plan Generated'), ('plan_approved', 'Plan Approved'), ('repository_confirmed', 'Repository Confirmed'), ('branch_created', 'Branch Created'), ('context_prepared', 'Context Prepared'), ('change_proposal_generated', 'Change Proposal Generated'), ('changes_reviewed', 'Changes Reviewed'), ('pr_draft_created', 'PR Draft Created'), ('review_pending', 'Review Pending'), ('review_approved', 'Review Approved'), ('deployment_pending', 'Deployment Pending'), ('deployed_to_development', 'Deployed to Development'), ('rework_required', 'Rework Required'), ('closed', 'Closed'), ('failed', 'Failed')], db_index=True, default='session_created', max_length=50)),
                ('previous_state', models.CharField(blank=True, max_length=50)),
                ('jira_issue_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('jira_issue_data', models.JSONField(blank=True, default=dict)),
                ('repository_url', models.URLField(blank=True)),
                ('repository_name', models.CharField(blank=True, max_length=300)),
                ('target_branch', models.CharField(blank=True, default='main', max_length=300)),
                ('working_branch', models.CharField(blank=True, max_length=300)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_runs', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('publish_state', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('is_system_template', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_templates', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='accounts.team')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('definition', models.JSONField()),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_versions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflows.workflowtemplate')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_id', models.UUIDField(default=uuid.uuid4)),
                ('step_type', models.CharField(choices=[('agent', 'Agent Task'), ('mcp_tool', 'MCP Tool Call'), ('mcp_resource', 'MCP Resource Fetch'), ('approval', 'Human Approval'), ('condition', 'Condition Branch'), ('notification', 'Notification'), ('pr_action', 'PR Action'), ('deploy_action', 'Deploy Action')], max_length=30)),
                ('step_name', models.CharField(max_length=300)),
                ('node_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('awaiting_approval', 'Awaiting Approval')], default='pending', max_length=30)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflowrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='workflows.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='workflows.workflowtemplateversion'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['state', 'created_at'], name='workflows_w_state_f35caa_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['initiated_by', 'state'], name='workflows_w_initiat_1617d8_idx'),
        ),
    ]
