# Generated by Django 4.2.16 on 2026-03-23 02:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('story_analysis', 'Story Analysis Agent'), ('implementation_planning', 'Implementation Planning Agent'), ('context_retrieval', 'Context Retrieval Agent'), ('code_proposal', 'Code Proposal Agent'), ('test_generation', 'Test Generation Agent'), ('pr_packaging', 'PR Packaging Agent'), ('review_readiness', 'Review Readiness Agent'), ('deployment_readiness', 'Deployment Readiness Agent')], max_length=50)),
                ('agent_version', models.CharField(default='1.0', max_length=50)),
                ('llm_provider', models.CharField(max_length=50)),
                ('llm_model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('system_prompt', models.TextField(blank=True)),
                ('user_prompt', models.TextField(blank=True)),
                ('raw_response', models.TextField(blank=True)),
                ('structured_output', models.JSONField(blank=True, null=True)),
                ('output_schema_version', models.CharField(default='1.0', max_length=20)),
                ('tool_calls_summary', models.JSONField(blank=True, default=list)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('step_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='workflows.workflowsteprun')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
