# Generated by Django 4.2.16 on 2026-03-23 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequestRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_pr_id', models.CharField(blank=True, max_length=100)),
                ('external_pr_number', models.PositiveIntegerField(blank=True, null=True)),
                ('repository_url', models.URLField()),
                ('repository_name', models.CharField(max_length=300)),
                ('source_branch', models.CharField(max_length=300)),
                ('target_branch', models.CharField(default='main', max_length=300)),
                ('pr_url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('merged', 'Merged'), ('closed', 'Closed'), ('declined', 'Declined')], default='draft', max_length=30)),
                ('diff_summary', models.JSONField(blank=True, default=dict)),
                ('files_changed', models.PositiveSmallIntegerField(default=0)),
                ('lines_added', models.PositiveIntegerField(default=0)),
                ('lines_removed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_prs', to=settings.AUTH_USER_MODEL)),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_prs', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pull_requests', to='workflows.workflowrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
