# Generated by Django 4.2.16 on 2026-03-23 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('actor_role', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('workflow', 'Workflow'), ('agent', 'Agent Execution'), ('mcp_call', 'MCP Tool Call'), ('approval', 'Approval'), ('pr', 'Pull Request'), ('deployment', 'Deployment'), ('policy', 'Policy Enforcement'), ('admin', 'Administration')], db_index=True, max_length=30)),
                ('action', models.CharField(db_index=True, max_length=300)),
                ('result', models.CharField(max_length=50)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=200)),
                ('target_description', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='workflows.workflowrun')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category', 'timestamp'], name='audit_audit_categor_329c61_idx'), models.Index(fields=['actor', 'timestamp'], name='audit_audit_actor_i_573746_idx'), models.Index(fields=['workflow_run', 'timestamp'], name='audit_audit_workflo_61e053_idx')],
            },
        ),
    ]
