# Generated by Django 4.2.16 on 2026-03-23 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('plan_approval', 'Implementation Plan Approval'), ('branch_create', 'Branch Creation'), ('code_review', 'Code Change Review'), ('pr_create', 'Pull Request Creation'), ('pr_review', 'Pull Request Review'), ('deploy_to_dev', 'Deploy to Development'), ('custom_flow_publish', 'Custom Flow Publish')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('timed_out', 'Timed Out'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('required_role', models.CharField(blank=True, max_length=50)),
                ('decision_notes', models.TextField(blank=True)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflows.workflowrun')),
                ('step_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflows.workflowsteprun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='approvals_a_status_65ce49_idx'), models.Index(fields=['run', 'action_type'], name='approvals_a_run_id_2aaa22_idx')],
            },
        ),
    ]
