# Generated by Django 4.2.16 on 2026-03-23 02:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability_type', models.CharField(choices=[('tool', 'Tool'), ('prompt', 'Prompt'), ('resource', 'Resource')], max_length=20)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('access_level', models.CharField(choices=[('read_only', 'Read Only'), ('write_capable', 'Write Capable'), ('approval_required', 'Approval Required'), ('environment_sensitive', 'Environment Sensitive')], default='read_only', max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_unknown_write', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('last_discovered_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'MCP Capabilities',
                'ordering': ['capability_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MCPToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_call_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('arguments_redacted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], max_length=20)),
                ('response', models.JSONField(blank=True, null=True)),
                ('response_redacted', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('invoked_at', models.DateTimeField(auto_now_add=True)),
                ('approval_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_calls', to='approvals.approvalrecord')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='mcp_client.mcpcapability')),
                ('step_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_calls', to='workflows.workflowsteprun')),
            ],
            options={
                'ordering': ['-invoked_at'],
            },
        ),
    ]
