# Generated by Django 4.2.16 on 2026-03-23 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pull_requests', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('development', 'Development')], default='development', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('external_pipeline_id', models.CharField(blank=True, max_length=300)),
                ('pipeline_url', models.URLField(blank=True)),
                ('commit_sha', models.CharField(blank=True, max_length=100)),
                ('artifact_name', models.CharField(blank=True, max_length=300)),
                ('artifact_version', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('deployment_log_url', models.URLField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deployments', to=settings.AUTH_USER_MODEL)),
                ('deployed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to=settings.AUTH_USER_MODEL)),
                ('pull_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='pull_requests.pullrequestrecord')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='workflows.workflowrun')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
